import { AssetStoreConfig } from "../src/config"

const bucket: string = 'contentstack-lextegrity-test-automation-asset-store'

export const config :AssetStoreConfig = {
  assetStore: {
    region: 'eu-west-1', // Required
    apiVersion: '2006-03-01', // Required
    // `apiVersion`, `apiKey` and `downloadId` can be generated by using an asset's url pattern
    pattern: '/:apiKey/:uid/:downloadId/:filename',
    bucketParams: {
      ACL: 'private',
      Bucket: bucket
    }
  }
}
